project:
  title: "Wind Energy Group"
  output-dir: ./_site/en

website:
  navbar:
    left:
        href: research.qmd
        text: Publications
      - href: services.qmd        
        text: Services and Courses
      - href: career.qmd
        text: Wind Power Specialist
    right:
      - href: ../es
        text: Español
      - href: ../en
        text: English

lang: en

  page-footer: 
    background: primary
    left: "Copyright 2024, Osvaldo Rodríguez. "
    
   
format:
  html:
    toc-title: Content
    toc: true
    toc-depth: 4
    theme:
        light: ier_claro.scss
        dark: ier_dark.scss
    css: styles.css
    page-layout: full